[package]
name = "lorawan-pilot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lorawan = { version = "0.1.0", git = "https://github.com/lucasgranberg/lorawan.git", features = [
    "defmt",
] }
embassy-lora = { version = "0.1.0", git = "https://github.com/lucasgranberg/embassy.git", rev = "2fe352272ad56a6ca30d0b7940c2660af67137a7", features = [
    "stm32wl",
    "time",
] }
embassy-sync = { version = "0.2.0", git = "https://github.com/lucasgranberg/embassy.git", rev = "2fe352272ad56a6ca30d0b7940c2660af67137a7", features = [
    "defmt",
] }
embassy-executor = { version = "0.2.0", git = "https://github.com/lucasgranberg/embassy.git", rev = "2fe352272ad56a6ca30d0b7940c2660af67137a7", features = [
    "defmt",
    "integrated-timers",
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "nightly",
] }
embassy-time = { version = "0.1.0", git = "https://github.com/lucasgranberg/embassy.git", rev = "2fe352272ad56a6ca30d0b7940c2660af67137a7", features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-32_768",
    "unstable-traits",
    "nightly",
] }
embassy-stm32 = { version = "0.1.0", git = "https://github.com/lucasgranberg/embassy.git", rev = "2fe352272ad56a6ca30d0b7940c2660af67137a7", features = [
    "nightly",
    "defmt",
    "time-driver-any",
    "memory-x",
    "unstable-pac",
    "exti",
    "unstable-traits",
    "stm32wl55jc-cm4",
] }
embassy-embedded-hal = { version = "0.1.0", git = "https://github.com/lucasgranberg/embassy.git", rev = "2fe352272ad56a6ca30d0b7940c2660af67137a7" }
embassy-hal-common = { version = "0.1.0", git = "https://github.com/lucasgranberg/embassy.git", rev = "2fe352272ad56a6ca30d0b7940c2660af67137a7", default-features = false }
embedded-hal-async = { version = "=0.2.0-alpha.2" }

embedded-storage = { version = "0.3.0", default-features = false }

defmt = "0.3.4"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
embedded-hal = "0.2.7"
panic-probe = { version = "0.3", features = ["print-defmt"] }
panic-reset = { version = "0.1.1" }
futures = { version = "0.3.25", default-features = false, features = [
    "async-await",
] }
heapless = { version = "0.7.16", default-features = false }
rand_core = { version = "0.6.2", default-features = false }
lora-phy = { version = "2" }
