[package]
name = "lorawan-pilot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lorawan = { version = "0.1.0", features = ["defmt", "serde"] }
embassy-lora = { version = "0.1.0", features = ["stm32wl"] }
embassy-sync = { version = "0.2.0", features = ["defmt"] }
embassy-executor = { version = "0.2.0", features = ["defmt", "integrated-timers", "arch-cortex-m", "executor-thread", "executor-interrupt", "nightly"] }
embassy-time = { version = "0.1.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768", "unstable-traits", "nightly"] }
embassy-stm32 = { version = "0.1.0", features = ["nightly", "defmt", "time-driver-any", "memory-x", "unstable-pac","exti", "unstable-traits", "stm32wl55jc-cm4"] }
embassy-embedded-hal = { version = "0.1.0" }

embedded-hal = "0.2.7"
embedded-hal-async = { version = "=0.2.0-alpha.2" }
embedded-storage = { version = "0.3.0", default-features = false }

defmt = "0.3.4"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"

panic-probe = { version = "0.3", features = ["print-defmt"] }
panic-reset = { version = "0.1.1" }
futures = { version = "0.3.25", default-features = false, features = [
    "async-await",
] }
rand_core = { version = "0.6.2", default-features = false }
lora-phy = { version = "2" }
postcard = "1.0.4"

[profile.release]
debug = 2

[patch.crates-io]
lorawan = { git = "https://github.com/lucasgranberg/lorawan.git", rev = "abc863cf72d474b139129298272a4020cdf4dedf" }
embassy-lora = { git = "https://github.com/ceekdee/embassy.git", rev = "24d3aed7ecb06007ba3d65f1b76dfe7bd57b3b87" }
embassy-sync = { git = "https://github.com/ceekdee/embassy.git", rev = "24d3aed7ecb06007ba3d65f1b76dfe7bd57b3b87" }
embassy-executor = { git = "https://github.com/ceekdee/embassy.git", rev = "24d3aed7ecb06007ba3d65f1b76dfe7bd57b3b87" }
embassy-time = { git = "https://github.com/ceekdee/embassy.git", rev = "24d3aed7ecb06007ba3d65f1b76dfe7bd57b3b87" }
embassy-stm32 = { git = "https://github.com/ceekdee/embassy.git", rev = "24d3aed7ecb06007ba3d65f1b76dfe7bd57b3b87" }
embassy-embedded-hal = { git = "https://github.com/ceekdee/embassy.git", rev = "24d3aed7ecb06007ba3d65f1b76dfe7bd57b3b87" }
