[package]
name = "lorawan-pilot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-stm32 = { version = "0.1.0", features = ["nightly", "unstable-traits", "defmt", "stm32wl55jc-cm4", "time-driver-any", "memory-x", "unstable-pac", "exti", "chrono"] }
embassy-sync = { version = "0.3.0", features = ["defmt"] }
embassy-executor = { version = "0.3.0", features = ["nightly", "arch-cortex-m", "executor-thread", "defmt", "integrated-timers"] }
embassy-time = { version = "0.1.3", features = ["nightly", "unstable-traits", "defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-embedded-hal = { version = "0.1.0" }
embassy-lora = { version = "0.1.0", features = ["stm32wl"] }
lora-phy = { version = "2" }
lorawan = { version = "0.1.0", features = ["defmt", "serde"] }

defmt = "0.3"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.3"
embedded-hal = "0.2.7"
embedded-hal-async = { version = "=1.0.0-rc.1" }
embedded-storage = { version = "0.3.0", default-features = false }

panic-probe = { version = "0.3", features = ["print-defmt"] }
panic-reset = { version = "0.1.1" }
futures = { version = "0.3.25", default-features = false, features = ["async-await"] }
heapless = { version = "0.7.16", default-features = false }
chrono = { version = "^0.4", default-features = false }
rand_core = { version = "0.6.2", default-features = false }

serde = { version = "1.0.163", default-features = false, features = ["derive"] }
postcard = "1.0.4"

[profile.release]
debug = 2

[patch.crates-io]
embassy-stm32 = { git = "https://github.com/ceekdee/embassy.git", rev = "b8894514edc5d470f09d21caaa992454e6c2f05c" }
embassy-sync = { git = "https://github.com/ceekdee/embassy.git", rev = "b8894514edc5d470f09d21caaa992454e6c2f05c" }
embassy-executor = { git = "https://github.com/ceekdee/embassy.git", rev = "b8894514edc5d470f09d21caaa992454e6c2f05c" }
embassy-time = { git = "https://github.com/ceekdee/embassy.git", rev = "b8894514edc5d470f09d21caaa992454e6c2f05c" }
embassy-embedded-hal = { git = "https://github.com/ceekdee/embassy.git", rev = "b8894514edc5d470f09d21caaa992454e6c2f05c" }
embassy-lora = { git = "https://github.com/ceekdee/embassy.git", rev = "b8894514edc5d470f09d21caaa992454e6c2f05c" }
lorawan = { git = "https://github.com/lucasgranberg/lorawan.git", rev = "0ab0a20d99647cb87322fa0e7e670932ee67ebe2" }
