[package]
name = "lorawan-pilot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lorawan = { version = "0.1.0", path = "../lucasgranberg/lorawan", features = [
    "defmt",
] }
embassy-sync = { version = "0.1.0", path = "../embassy/embassy-sync", features = [
    "defmt",
] }
embassy-executor = { version = "0.1.0", path = "../embassy/embassy-executor", features = [
    "defmt",
    "integrated-timers",
] }
embassy-time = { version = "0.1.0", path = "../embassy/embassy-time", features = [
    "defmt",
    "defmt-timestamp-uptime",
    "tick-hz-32_768",
] }
embassy-stm32 = { version = "0.1.0", path = "../embassy/embassy-stm32", features = [
    "nightly",
    "defmt",
    "time-driver-any",
    "memory-x",
    "subghz",
    "unstable-pac",
    "exti",
    "unstable-traits",
    "stm32wl55jc-cm4",
] }
embassy-embedded-hal = { version = "0.1.0", path = "../embassy/embassy-embedded-hal" }
embassy-hal-common = { version = "0.1.0", path = "../embassy/embassy-hal-common", default-features = false }


postcard = { version = "1.0.2" }
serde = { version = "1.0.152", default-features = false }
embedded-storage = { version = "0.3.0", default-features = false }

defmt = "0.3"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-hal = "0.2.7"
panic-probe = { version = "0.3", features = ["print-defmt"] }
panic-abort = "0.3.2"
futures = { version = "0.3.25", default-features = false, features = [
    "async-await",
] }
heapless = { version = "0.7.16", default-features = false }
rand_core = { version = "0.6.2", default-features = false }
